<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-VKAG1RPA" failures="0" tests="2" name="com.extraPOSTest.testCases.Approvals.TC_ApprovalRoleCode" time="6.281" errors="1" timestamp="2021-03-12T13:23:38 IST" skipped="0">
  <testcase classname="com.extraPOSTest.testCases.Approvals.TC_ApprovalRoleCode" name="selectALL_forApprovalRoleCode" time="6.281"/>
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.Approvals.TC_ApprovalRoleCode" name="createApprovalRoleCode" time="0.000">
    <error message="
Method public void com.extraPOSTest.testCases.Approvals.TC_ApprovalRoleCode.createApprovalRoleCode() requires a @DataProvider named : addApprovalRoleCode" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Method public void com.extraPOSTest.testCases.Approvals.TC_ApprovalRoleCode.createApprovalRoleCode() requires a @DataProvider named : addApprovalRoleCode
at org.testng.internal.Parameters.findDataProvider(Parameters.java:559)
at org.testng.internal.Parameters.handleParameters(Parameters.java:772)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:789)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- createApprovalRoleCode -->
  <system-out/>
</testsuite> <!-- com.extraPOSTest.testCases.Approvals.TC_ApprovalRoleCode -->
